[workspace]

[package]
name = "my_switch"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
switch_program_sdk = { path = "../switch_program_sdk" }
postcard = { version = "1", default-features = false, features = ["alloc"] }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }

[profile.release]
opt-level = "s"
lto = true
strip = true
